/*

 */

package superdetodosa;

import java.util.Iterator;
import java.util.TreeSet;
import javax.swing.JOptionPane;
import static superdetodosa.Categoria.COMESTIBLE;
import static superdetodosa.Categoria.LIMPIEZA;
import static superdetodosa.Categoria.PERFUMERIA;
import static superdetodosa.Categoria.SELECCIONE;

/**
 *
 * @author Your Name <your.name at your.org>
 */
public class GestionDeProductosView extends javax.swing.JInternalFrame {
//    public static TreeSet<Producto> baseDatos = new TreeSet<Producto>();
    
    /** Creates new form GestionDeProductosView */
    public GestionDeProductosView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jtDescripcion = new javax.swing.JTextField();
        jtPrecio = new javax.swing.JTextField();
        jcbCategoria = new javax.swing.JComboBox<>();
        jtStock = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("GESTION DE PRODUCTOS");

        jLabel2.setText("Código:");

        jLabel3.setText("Descripción:");

        jLabel4.setText("Precio:");

        jLabel5.setText("Rubro:");

        jLabel6.setText("Stock:");

        jcbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new Categoria[] { SELECCIONE,COMESTIBLE, LIMPIEZA, PERFUMERIA}));
        jcbCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jbBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTIN\\Desktop\\Argentina Programa 4.0\\JAVA-Creando Una Aplicacion\\Guia2\\SuperDeTodoSA\\buscar.png")); // NOI18N
        jbBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbBuscar.setPreferredSize(new java.awt.Dimension(289, 265));
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbNuevo.setText("Nuevo");
        jbNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbSalir)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtDescripcion)
                                        .addComponent(jcbCategoria, 0, 236, Short.MAX_VALUE)
                                        .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(40, 40, 40)
                                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEliminar)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo)
                    .addComponent(jbGuardar)
                    .addComponent(jbEliminar)
                    .addComponent(jbSalir))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
            try{  
            if(jtCodigo.getText().isEmpty()||jtDescripcion.getText().isEmpty()||jtPrecio.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "No debe haber campos vacíos.");
                return;
            }else if(jcbCategoria.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(this, "Elegir una categoría.");
                return;
            }
            
            int codigo = Integer.parseInt(jtCodigo.getText());
            String descripcion = jtDescripcion.getText();
            double precio = Double.parseDouble(jtPrecio.getText());
            int stock = Integer.parseInt(jtStock.getText());
            Categoria rubro = (Categoria) jcbCategoria.getSelectedItem();
            
            Producto prod = new Producto(codigo, descripcion, precio, stock, rubro);
            
            for (Producto j : Menu.baseDatos) {
            if (jtCodigo.getText().equalsIgnoreCase(String.valueOf(j.getCodigo()))) {
                JOptionPane.showMessageDialog(this, "Código ya existe. Ir a 'GUARDAR'");
                return;
            }
        }
            cargarBase(prod);

            }catch(NumberFormatException numb){
                JOptionPane.showMessageDialog(this, "Código y/o Precio deben ser números.");
                return;
            }
            
            jtCodigo.setText("");
            jtDescripcion.setText("");
            jtPrecio.setText("");
            jcbCategoria.setSelectedIndex(0);
            jtStock.setText("");
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
       buscarBase();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        try {
            if (jtCodigo.getText().isEmpty() || jtDescripcion.getText().isEmpty() || jtPrecio.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No debe haber campos vacíos.");
                return;
            } else if (jcbCategoria.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Elegir una categoría.");
                return;
            }

            for (Producto k : Menu.baseDatos) {
                if (jtCodigo.getText().equalsIgnoreCase(String.valueOf(k.getCodigo()))) {
                    k.setCodigo(Integer.parseInt(jtCodigo.getText()));
                    k.setDescripcion(jtDescripcion.getText());
                    k.setPrecio(Double.parseDouble(jtPrecio.getText()));
                    k.setRubro((Categoria) jcbCategoria.getSelectedItem());
                    k.setStock(Integer.parseInt(jtStock.getText()));
                }/*else if(!jtCodigo.getText().equalsIgnoreCase(String.valueOf(k.getCodigo()))){
                    Si se quiere oprimir 'GUARDAR' a un producto que no está en el TreeSet se mostrará el sig. msj.
                    JOptionPane.showMessageDialog(this, "Producto nuevo. Ir a 'NUEVO'");
                    return;
                }*/
            }

        } catch (NumberFormatException numb) {
            JOptionPane.showMessageDialog(this, "Código y/o Precio deben ser números.");
            return;
        }

        jtCodigo.setText("");
        jtDescripcion.setText("");
        jtPrecio.setText("");
        jcbCategoria.setSelectedIndex(0);
        jtStock.setText("");
        jtCodigo.setEditable(true);
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        
                Iterator<Producto> it=Menu.baseDatos.iterator();
                    while(it.hasNext()){
                    if(it.next().getCodigo()==Integer.parseInt(jtCodigo.getText())){
                        it.remove();
                    }
                    }
         
        jtCodigo.setText("");
        jtDescripcion.setText("");
        jtPrecio.setText("");
        jcbCategoria.setSelectedIndex(0);
        jtStock.setText("");
        jtCodigo.setEditable(true);
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Categoria> jcbCategoria;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtDescripcion;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTextField jtStock;
    // End of variables declaration//GEN-END:variables


    private void cargarBase(Producto prod) {
        Menu.baseDatos.add(new Producto(prod.getCodigo(), prod.getDescripcion(), prod.getPrecio(), prod.getStock(), prod.getRubro()));

    }

    private void buscarBase() {
        for (Producto i : Menu.baseDatos) {
            if (jtCodigo.getText().equalsIgnoreCase(String.valueOf(i.getCodigo()))) {
                jtCodigo.setEditable(false);//Cuando hay coincidencia bloquea el campo 'código'
                jtDescripcion.setText(i.getDescripcion());
                jtPrecio.setText(String.valueOf(i.getPrecio()));
                jcbCategoria.setSelectedItem(i.getRubro());
                jtStock.setText(String.valueOf(i.getStock()));
            }
        }
    }

    private void duplicados() {
        for (Producto j : Menu.baseDatos) {
            if (jtCodigo.getText().equalsIgnoreCase(String.valueOf(j.getCodigo()))) {
                JOptionPane.showMessageDialog(this, "Código de producto ya existe.");
            }
        }
    }
    
}
