/*

 */
package superdetodosa;

import java.awt.Graphics;
import java.awt.Image;
import java.util.TreeSet;
import javax.swing.ImageIcon;
import static superdetodosa.Categoria.COMESTIBLE;
import static superdetodosa.Categoria.LIMPIEZA;
import static superdetodosa.Categoria.PERFUMERIA;

/**
 *
 * @author Your Name <your.name at your.org>
 */
public class Menu extends javax.swing.JFrame {
    public static TreeSet<Producto> baseDatos=new TreeSet<>();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/img/logoSuper.png"));
        Image image = icon.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmProductos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmPorRubro = new javax.swing.JMenuItem();
        jmPorNombre = new javax.swing.JMenuItem();
        jmPorPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        jMenu1.setText("Administración");

        jmProductos.setText("Productos");
        jmProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmProductosActionPerformed(evt);
            }
        });
        jMenu1.add(jmProductos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        jmPorRubro.setText("Por Rubro");
        jmPorRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPorRubroActionPerformed(evt);
            }
        });
        jMenu2.add(jmPorRubro);

        jmPorNombre.setText("Por Nombre");
        jmPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPorNombreActionPerformed(evt);
            }
        });
        jMenu2.add(jmPorNombre);

        jmPorPrecio.setText("Por Precio");
        jmPorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPorPrecioActionPerformed(evt);
            }
        });
        jMenu2.add(jmPorPrecio);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPorNombreActionPerformed
        // TODO add your handling code here:
        //Acá se asocia el javaInternalFrame 'BusquedaPorNombreView'
        escritorio.removeAll();
        escritorio.repaint();
        BusquedaPorNombreView bpn=new BusquedaPorNombreView();//instancia de ventana
        bpn.setVisible(true);//hace visible la ventana
        escritorio.add(bpn);//abre la ventana
        escritorio.moveToFront(bpn);//trae al frente la ventana
    }//GEN-LAST:event_jmPorNombreActionPerformed

    private void jmProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmProductosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        GestionDeProductosView gdp=new GestionDeProductosView();//instancia de ventana
        gdp.setVisible(true);//hace visible la ventana
        escritorio.add(gdp);//abre la ventana
        escritorio.moveToFront(gdp);//trae al frente la ventana
    }//GEN-LAST:event_jmProductosActionPerformed

    private void jmPorRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPorRubroActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BusquedaPorRubroView bpr=new BusquedaPorRubroView();//instancia de ventana
        bpr.setVisible(true);//hace visible la ventana
        escritorio.add(bpr);//abre la ventana
        escritorio.moveToFront(bpr);//trae al frente la ventana
    }//GEN-LAST:event_jmPorRubroActionPerformed

    private void jmPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPorPrecioActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BusquedaPorPrecioView bpp=new BusquedaPorPrecioView();//instancia de ventana
        bpp.setVisible(true);//hace visible la ventana
        escritorio.add(bpp);//abre la ventana
        escritorio.moveToFront(bpp);//trae al frente la ventana
    }//GEN-LAST:event_jmPorPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmPorNombre;
    private javax.swing.JMenuItem jmPorPrecio;
    private javax.swing.JMenuItem jmPorRubro;
    private javax.swing.JMenuItem jmProductos;
    // End of variables declaration//GEN-END:variables

    private void cargarProductos(){
        baseDatos.add(new Producto(10,"Azucar x 1kg",300.2,150,COMESTIBLE));
        baseDatos.add(new Producto(12,"Yerba Taragui 1kg",850.3,300,COMESTIBLE));
        baseDatos.add(new Producto(14,"Aceite Canuelas 900cc",450.1,250,COMESTIBLE));
        baseDatos.add(new Producto(15,"Lavandina Ayudín 1L",373.0,400,LIMPIEZA));
        baseDatos.add(new Producto(16,"Detergente Cif 430ml",390.3,480,LIMPIEZA));
        baseDatos.add(new Producto(15,"Jabon Liquido Ala 3L",849.0,200,LIMPIEZA));
        baseDatos.add(new Producto(15,"Jabon Dove 35gr",399.0,500,PERFUMERIA));
        baseDatos.add(new Producto(15,"Shampoo H&S 400ml",750.0,600,PERFUMERIA));
        baseDatos.add(new Producto(15,"Acondicionador H&S 400ml",750.0,400,PERFUMERIA));
        
    }

}
